changelog:
  exclude:
    labels:
      - exclude from release

  categories:
    - title: Breaking Changes
      labels:
        - breaking change

    - title: Features
      labels:
        - feature

    - title: Bug Fixes
      labels:
        - bug fix

    - title: Dependencies
      labels:
        - dependency change

    - title: Other Changes
      labels:
        - change
