name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  job_lint_test_build:
    name: Lint, Test and Build
    uses: ./.github/workflows/lint-test-build.yml

  job_upload_coverage:
    name: Upload Coverage

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch'
    needs: job_lint_test_build

    steps:
      - name: Checkout, Setup Node.js v${{ env.NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 20.x

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage-final.json


  job_create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: job_lint_test_build

    permissions:
      contents: write

    steps:
      - name: Checkout, Setup Node.js v${{ env.NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.NODE_VERSION }}
        env:
          NODE_VERSION: 20.x

      - name: Build
        run: npm run build

      - name: Create tarball
        run: npm pack

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: rollup-plugin-spawn-process-*.tgz

  job_publish_to_npm:
    name: Publish Package to npm

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: job_lint_test_build

    steps:
      - name: Checkout, Setup Node.js v${{ env.NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_VERSION: 20.x

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  job_publish_to_gpr:
    name: Publish to Github Packages

    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
    needs: job_lint_test_build

    permissions:
      packages: write

    steps:
      - name: Checkout, Setup Node.js v${{ env.NODE_VERSION }} and Install dependencies
        uses: manferlo81/action-checkout-node-install@v0
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_VERSION: 20.x

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
