name: Lint, Test and Build

on:
  workflow_call:

jobs:
  job_lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  job_ci:
    strategy:
      matrix:
        os:
          - name: Ubuntu
            image: ubuntu-latest
          - name: macOS
            image: macos-latest
          - name: Windows
            image: windows-latest

        node-version:
          - 18.x
          - 20.x

    name: Test and Build (${{ matrix.os.name }}, Node.js ${{ matrix.node-version }})

    runs-on: ${{ matrix.os.image }}
    needs: job_lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
